[custom]
ruleset=OpenAI,https://rule.kelee.one/Clash/OpenAI.yaml
ruleset=中国光明,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
ruleset=中国光明,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMax/ChinaMax_Domain_For_Clash.txt
ruleset=中国光明,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMax/ChinaMax.list
ruleset=中国光明,https://rule.kelee.one/Clash/ChinaMax.yaml
ruleset=SteamCN,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list
ruleset=Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.list
ruleset=国际互联,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=国际互联,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global_Domain_For_Clash.txt
ruleset=国际互联,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=国际互联,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia_Domain_For_Clash.txt
ruleset=中国光明,[]GEOIP,CN
ruleset=漏网之鱼,[]FINAL
######################################################################################################
custom_proxy_group=漏网之鱼`select`[]DIRECT`[]登机咯
custom_proxy_group=中国光明`select`[]DIRECT`[]登机咯
custom_proxy_group=国际互联`select`[]登机咯
custom_proxy_group=OpenAI`select`[]登机咯
custom_proxy_group=Steam`select`[]DIRECT`[]登机咯
custom_proxy_group=SteamCN`select`[]DIRECT`[]登机咯
custom_proxy_group=登机咯`select`.*
######################################################################################################
enable_rule_generator=true
overwrite_original_rules=true
