[custom]
ruleset=OpenAI,https://rule.kelee.one/Clash/OpenAI.yaml
ruleset=局域网,https://rule.kelee.one/Clash/Lan.yaml
ruleset=局域网,https://rule.kelee.one/Clash/ChinaMax.yaml
ruleset=SteamCN,https://rule.kelee.one/Clash/SteamCN.yaml
ruleset=Steam,https://rule.kelee.one/Clash/Steam.yaml
ruleset=互联网,https://rule.kelee.one/Clash/Global.yaml
ruleset=互联网,https://rule.kelee.one/Clash/GlobalMedia.yaml
ruleset=漏网之鱼,[]FINAL
######################################################################################################
custom_proxy_group=漏网之鱼`select`[]DIRECT`[]登机咯
custom_proxy_group=中国光明`select`[]DIRECT`[]登机咯
custom_proxy_group=国际互联`select`[]登机咯
custom_proxy_group=OpenAI`select`[]登机咯
custom_proxy_group=Steam`select`[]DIRECT`[]登机咯
custom_proxy_group=SteamCN`select`[]DIRECT`[]登机咯
custom_proxy_group=登机咯`select`.*
######################################################################################################
enable_rule_generator=true
overwrite_original_rules=true
